### ISSUE TITLE
Version 0.6.10 Doesn't work with tmux 1.8?

### ISSUE THREAD

**Issue by ReggiePuksta** [tmuxinator/tmuxinator#289]
Hi I have installed default tmuxinator through gems. But it gave me an error when I tried to open a session: 

tmux: unknown option -- c
usage: new-session [-AdDP] [-F format] [-n window-name] [-s session-name] [-t target-session] [-x width] [-y height] [command]
failed to connect to server
failed to connect to server
failed to connect to server
failed to connect to server
failed to connect to server
failed to connect to server
failed to connect to server
failed to connect to server
failed to connect to server
failed to connect to server
failed to connect to server
failed to connect to server
failed to connect to server
no sessions

I am using 1.8 tmux and 0.6.10 tmuxinator.
By removing tmuxinator and installing the 0.6.9 version, session was created with no errors.
I wonder if it doesn't support tmux 1.8 as of the newest version?

**Comment by jwgoh** [comment]
+1
I downgraded and am using 0.6.9 for now. No zsh completion though :(
On a sidenote, I updated the psych gem v2.0.13 and tmuxinator gives me "Failed to parse config file. Please check your formatting." error. I removed the update and currently using v2.0.8, and it works perfectly fine. Any ideas?

**Comment by Soliah** [comment]
I'll see if I can have a look tonight.

@jwgoh psych is the default YAML parser in Ruby so I'd imagine something changed. Could you raise another issue and paste your project YAML?

**Comment by janv** [comment]
:+1: 
Seems to be cause by this merge: https://github.com/tmuxinator/tmuxinator/commit/8b4255f0fc5aa9673228085f95a891579a6eb5b1

**Comment by fbertux** [comment]
With this version [tmux-stable](https://launchpad.net/~pg-radadia/+archive/ubuntu/tmux-stable) is working.

**Comment by alshain** [comment]
I get the exact same error, running tmux 1.8 and tmuxinator 0.6.10

**Comment by fin-8** [comment]
The same here, tmux 1.8-5 and tmuxinator 0.6.10 on Linux Mint 17.1

**Comment by fbertux** [comment]
Looking on [changelog](http://sourceforge.net/p/tmux/tmux-code/ci/master/tree/CHANGES) the option -c is incompatible with version 1.8.
On Ubuntu you can use this ppa [tmux-stable](https://launchpad.net/~pg-radadia/+archive/ubuntu/tmux-stable)

**Comment by Soliah** [comment]
I've just pushed 0.6.11.pre which increases the version to not use `-c` to include 1.8. Appreciate testing to see if it works.

```
gem install tmuxinator -v 0.6.11.pre
```

**Comment by ReggiePuksta** [comment]
I am still getting some errors:

usage: new-session [-AdDP] [-F format] [-n window-name] [-s session-name] [-t target-session] [-x width] [-y height] [command]
failed to connect to server
failed to connect to server
failed to connect to server
failed to connect to server
usage: split-window [-dhvP] [-c start-directory] [-F format] [-p percentage|-l size] [-t target-pane] [command]
failed to connect to server
failed to connect to server
failed to connect to server
failed to connect to server
failed to connect to server
failed to connect to server
failed to connect to server
failed to connect to server
no sessions

I didn't mention that I am using Ubuntu 14.04

**Comment by fin-8** [comment]
The session is being created, but `mux` fails to create secondary windows.
Obviously, in this case a split isn't posible either, for the window doesn't not exist.

```
usage: new-window [-adkP] [-c start-directory] [-F format] [-n window-name] [-t target-window] [command]
window not found: webgui:2
usage: split-window [-dhvP] [-c start-directory] [-F format] [-p percentage|-l size] [-t target-pane] [command]
window not found: webgui:2
window not found: webgui:2
window not found: webgui:2
usage: split-window [-dhvP] [-c start-directory] [-F format] [-p percentage|-l size] [-t target-pane] [command]
window not found: webgui:2
window not found: webgui:2
window not found: webgui:2
window not found: webgui:2
window not found: webgui:2
```

**Comment by amosbird** [comment]
same problem in Centos 7 with fish-shell

**Comment by ndyakov** [comment]
I'm also affected by this.
```
➜ tmux -V
tmux 1.8
➜ tmuxinator -v
tmuxinator 0.6.10
```

**Comment by dfedde** [comment]
I have the same problems
OS:             Ubuntu
Tmux:         1.8
tmuxinator:  0.6.10

Tried using version 0.6.11.pre but still failed to create a session
```
usage: new-session [-AdDP] [-F format] [-n window-name] [-s session-name] [-t target-session] [-x width] [-y height] [command]
usage: new-window [-adkP] [-c start-directory] [-F format] [-n window-name] [-t target-window] [command]
failed to connect to server
failed to connect to server
failed to connect to server
usage: split-window [-dhvP] [-c start-directory] [-F format] [-p percentage|-l size] [-t target-pane] [command]
failed to connect to server
failed to connect to server
failed to connect to server
```
Went back to using version 0.6.9

**Comment by bimawa** [comment]
same trouble in mac os x pls fix it

**Comment by jeznet** [comment]
I have the same issue. Versions:
```
$ tmuxinator -v
tmuxinator 0.6.10
$ tmux -V
tmux 1.8
```

**Comment by SakuradaJun** [comment]
The same issue:

tmux: unknown option -- c
usage: new-session [-AdDP] [-F format] [-n window-name] [-s session-name] [-t target-session] [-x width] [-y height] [command]
session not found: scrapy_project:1
session not found: scrapy_project:0
session not found: scrapy_project:0
session not found: scrapy_project:0
session not found: scrapy_project:0
session not found: scrapy_project:0
session not found: scrapy_project:0
session not found: scrapy_project:0
session not found: scrapy_project:0
session not found: scrapy_project:1
session not found: scrapy_project

```
➜  ~  tmux -V
tmux 1.8
➜  ~  tmuxinator -v
tmuxinator 0.6.10

Ruby: 2.1.5
OS: Ubuntu 14.04
```

**Comment by bimawa** [comment]
now solve this trouble with next steps:

1. uninstall all tmuxinator versions: `gem uninstall tmuxinator`
2. install gem with version: `gem install tmuxinator -v 0.6.8`

**Comment by erickbarron** [comment]
@bimawa , yup that did it for me. It happened when I updated my Gems, so if you're thinking about updating your Gems, you will have to go back to one version of mux

**Comment by bimawa** [comment]
@erickbarron ^_^ sry i'm not maintainer of this repo.

**Comment by rightaway** [comment]
+1

**Comment by thikonom** [comment]
@bimawa 
Successfully installed tmuxinator-0.6.10
ERROR:  Could not find a valid gem '0.6.8' (>= 0) in any repository

**Comment by thikonom** [comment]
Works for me now too.
Ubuntu 14.04
Tmux 1.8
Tmuxinator 0.6.8

Thanks @bimawa

**Comment by Soliah** [comment]
Think I've dealt with this finally.
