### ISSUE TITLE
`.tmuxinator.yml` in ./ overrides mux basic functionality

### ISSUE THREAD

**Issue by hholst80** [tmuxinator/tmuxinator#431]
If you put a `.tmuxinator.yml` in the current directory you cannot use `mux help` or other commands instead tmuxinator auto-starts and/or attaches to the session defined in the local config.

version 0.7.0 (in Ubuntu 16.04 LTS)

**Comment by podung** [comment]
Confirmed on 0.7.1 also

**Comment by podung** [comment]
@adamstrickland thoughts?

**Comment by J3RN** [comment]
I think this should actually be pretty trivial. I'll revisit the logic in `/bin/tmuxinator` and see what goes on in there. Thanks for reporting!

**Comment by J3RN** [comment]
Oh gosh, I just realized that this is a v0.7.* issue. This was probably resolved in the v0.8.0 release. @hholst80 Is there any reason you haven't updated to a later version?

**Comment by ethagnawl** [comment]
I'm still seeing this on 0.8.1.

![local-before](https://cloud.githubusercontent.com/assets/289949/17010425/d4b4459c-4ed1-11e6-9fd0-5556f190f0d2.png)
![local_after](https://cloud.githubusercontent.com/assets/289949/17010424/d4b29652-4ed1-11e6-8eb4-633eb4df1ea8.png)

**Comment by adamstrickland** [comment]
🐛

**Comment by jpaugh** [comment]
Still seeing this in `0.10.0`. However, some commands *do* work.

These do not work:

    $ mux -v
    $ mux help

These commands do work:

* `version`
* `list`
* `commands`

I haven't tried any other commands, because I haven't learned what they do, yet.

**Comment by adamstrickland** [comment]
Crap...  I self-assigned this some time ago and totally flaked.  Sorry about that.

**Comment by jpaugh** [comment]
Life happens. That's okay. 

On December 7, 2017 3:52:53 PM CST, Adam Strickland <notifications@github.com> wrote:
>Crap...  I self-assigned this some time ago and totally flaked.  Sorry
>about that.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/tmuxinator/tmuxinator/issues/431#issuecomment-350105703

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
